export const categoriesTag = [
  'Ankle Boot',
  'Botas Femininas',
  'Cano Curto',
  'Cano Longo',
  'Cano Médio',
  'Chinelos',
  'Clogs',
  'Coturno',
  'Espadrilles',
  'Mocassins',
  'Mules',
  'Oxfords',
  'Papetes',
  'Rasteiras',
  'Sandálias',
  'Sapatilhas',
  'Scarpins',
  'Slides',
  'Tênis',
  'Tênis Sola Alta',
  'Tênis Sola Baixa',
];
